### ISSUE TITLE
Accepting Ship Positions 

### ISSUE THREAD

**Issue by Priyal1203** [Andi2610/battleship#6]
Take  and managing inputs ( i.e. all the ship positions) from 2 players after establishing connection

**Comment by Andi2610** [comment]
Ship positions are received in a string in a form of dictionary. Structure of dictionary is like { key{size of ship}  : value{starting coordinates of that ship,ship's orientation(horizontal or vertical))}. This dictionary is send by both the players and matrix object is created for both the players from these dictionaries.
